---

collections:
  - name: community.general
    version: 12.0.1

  - name: git+https://git@gitlab.purplejay.io/onboarding/endpoint-configuration.git#/pj
    type: git
    version: 0.0.4

  - name: git+https://git@gitlab.purplejay.io/keystone/ansible-collections.git
    type: git
    version: 1.3.6
